Add a basic country list select
winniepukki/bonvoyage pull request #72
Opened 2022-04-13 13:33 UTC by ymarkoff

- start using material icons
- create a basic Country List select

2022-04-13 13:45 UTC, winniepukki requested changes
@ymarkoff why did you check out from the `main` branch again, and not follow the commit and [branching strategy](https://docs.reaktivelab.co/getting-started/contribution#branching-strategy)? Please fix all merge conflicts

2022-04-13 13:45 UTC, winniepukki commented on components/ui/CountrySelect.js
> +    { code: 'AL', label: 'Albania', phone: '355' },
Please isolate this to a config file

2022-04-13 13:45 UTC, winniepukki commented on components/ui/CountrySelect.js
> +export default function CountrySelect() {
Please follow the current project export style:
```js
export const CountrySelect = () => (/* your code here */);

export default CountrySelect;
```

2022-04-13 13:45 UTC, winniepukki commented on components/ui/CountrySelect.js
> +        <StyledAutocomplete
Fix tabulation

2022-04-13 13:45 UTC, winniepukki commented on components/ui/CountrySelect.js
> +          id="country-select-demo"
Is there a reason for using the ID?

2022-04-13 13:45 UTC, winniepukki commented on components/ui/CountrySelect.js
> +                { option.phone }
Please use the Next JS image component

2022-04-13 13:45 UTC, winniepukki commented on components/ui/CountrySelect.js
> +                        <LocationOn style={ { color: '#2cc98a' } } />
Is there a reason for using the inline stylesheets?

2022-04-13 13:45 UTC, winniepukki commented on components/ui/CountrySelect.js
> +                        <CancelIcon style={ { color: '#c93130' } } />
Is there a reason for using the inline stylesheets?

2022-04-13 13:45 UTC, winniepukki commented on components/ui/index.js
> +export { default } from './countrySelect';
Please follow the project directory pattern. The `ui` dir is redundant.

2022-04-13 13:47 UTC, winniepukki commented
@ymarkoff your PR should go to the `staging` branch. Please fix, again...

2022-04-19 22:31 UTC, winniepukki requested changes
- Please rename the `config.json` to `countries.json`, since it doesn't have any configuration
- Please fix all branch issues. This should be merged to stating, not master

2022-04-19 22:31 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +import React from 'react';
No need for this import

2022-04-19 22:31 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +    const [, forceUpdate] = React.useReducer((x) => x + 1, 0);
Import this function directly from the library:
```js
import { useReducer } from 'react'
```

2022-04-19 22:31 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +    const textInput = React.useRef('');
Import this function directly from the library:
```js
import { useRef } from 'react'
```

2022-04-19 22:31 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +    }
Please use the state for managing the input value

2022-04-19 22:31 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +
Please use the state for managing the input value

2022-04-19 22:31 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +                    { option.phone }
I don't think that we really need phone numbers

2022-04-19 22:31 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +                      srcSet={ `https://flagcdn.com/w40/${option.code.toLowerCase()}.png 2x` }
Please avoid this monstrosity. Use destructuring, and check if those values for undefined
```js
const { code = '' } = option
```

2022-04-19 22:31 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +                  inputRef={ textInput }
Please use state for managing the input value

2022-04-19 22:31 UTC, winniepukki commented on package.json
> +    "@emotion/styled": "^11.8.1",
What is the need for using this?

2022-04-19 22:31 UTC, winniepukki commented on package.json
> +    "@mui/icons-material": "^5.6.1",
What is the need for using this?

2022-04-19 22:31 UTC, winniepukki commented on pages/_app.js
> +import { useEffect } from 'react/cjs/react.development';
Please use adequate imports

2022-04-19 22:31 UTC, winniepukki commented on pages/_app.js
> +
What does this monster do???

2022-04-19 22:31 UTC, winniepukki commented on pages/_document.js
> +      </Html>
Tabulation is golden

2022-04-19 22:31 UTC, winniepukki commented on pages/_document.js
> +};
What are you trying to achieve? Why is the eslint disabled?

2022-04-19 22:31 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +    const [, forceUpdate] = React.useReducer((x) => x + 1, 0);
Also, what are you trying to achieve?

2022-04-19 22:32 UTC, winniepukki commented
@ymarkoff deployment looks bronen

2022-04-19 23:17 UTC, ymarkoff commented on components/CountrySelect/countrySelect.js
> +    const [, forceUpdate] = React.useReducer((x) => x + 1, 0);
Refresh the values from Autocomplete should they be printed anywhere outside of the component, but maybe this is not needed at the moment, so I will remove it for the time being.

2022-04-19 23:18 UTC, ymarkoff commented on components/CountrySelect/countrySelect.js
> +    const textInput = React.useRef('');
Thanks, that looks much cleaner.

2022-04-19 23:20 UTC, ymarkoff commented on components/CountrySelect/countrySelect.js
> +
Can I do that with functional components?

2022-04-19 23:21 UTC, ymarkoff commented on package.json
> +    "@mui/icons-material": "^5.6.1",
Add the icons to the CountrySelect component following the design (Location icon and X icon).

2022-04-19 23:24 UTC, ymarkoff commented on pages/_document.js
> +      </Html>
Sorry, I used the automatic tabulation provided by VSC until the eslint was happy. Maybe my eslint hints are not synchronised with the Bonvoyage settings.

2022-04-19 23:27 UTC, ymarkoff commented on pages/_document.js
> +};
I was trying to apply external CSS sheets to fix some visual problems with the component, but since it didn't work I will just remove this file for now completely.

2022-04-19 23:28 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +
@ymarkoff https://codesandbox.io/s/headless-wave-wi5nen

2022-04-19 23:29 UTC, winniepukki commented on package.json
> +    "@mui/icons-material": "^5.6.1",
Why not import icons, and styling with CSS? Please remove those packages.

2022-04-20 00:51 UTC, ymarkoff commented on components/CountrySelect/countrySelect.js
> +    }
Refs seem to be a preferred way to manage user inputs, do you insist on moving this to state? https://dev.to/salehmubashar/useref-or-usestate-which-is-better-258j

2022-04-20 01:08 UTC, ymarkoff commented on pages/_app.js
> +import { useEffect } from 'react/cjs/react.development';
This code is now removed.

2022-04-20 01:09 UTC, ymarkoff commented on components/CountrySelect/countrySelect.js
> +
Thanks.

2022-04-20 01:09 UTC, ymarkoff commented on components/ui/CountrySelect.js
> +    { code: 'AL', label: 'Albania', phone: '355' },
Sorted.

2022-04-20 01:11 UTC, ymarkoff commented
> @ymarkoff deployment looks bronen

Deployment seems to be working now.

2022-04-20 01:13 UTC, ymarkoff commented
> @ymarkoff your PR should go to the `staging` branch. Please fix, again...

I'm not sure how I can change the PR to staging now that it is already open.

2022-04-20 01:14 UTC, ymarkoff commented
> @ymarkoff why did you check out from the `main` branch again, and not follow the commit and [branching strategy](https://docs.reaktivelab.co/getting-started/contribution#branching-strategy)? Please fix all merge conflicts

I actually checked out only the staging branch, but not the changes from main. I now have merged the changes from main into the branch too.

2022-04-20 06:23 UTC, winniepukki commented
Looks like the country select input field width doesn't follow the design

2022-04-20 11:37 UTC, winniepukki requested changes

2022-04-20 11:37 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +    }
Please use the state for managing the input value. You should also ideally utilize the business logic to a container, but just ignore it for now.

2022-04-20 11:37 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +
Please use the state for managing the input value.

2022-04-20 11:37 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +                      srcSet={ `https://flagcdn.com/w40/${option.code.toLowerCase()}.png 2x` }
Please do not ignore this message

2022-04-20 11:37 UTC, winniepukki commented on components/CountrySelect/countrySelect.js
> +                  inputRef={ textInput }
Same

2022-04-25 12:45 UTC, ymarkoff commented on components/CountrySelect/countrySelect.js
> +
Sorted

2022-04-25 12:49 UTC, winniepukki requested changes
@ymarkoff please fix previous messages as well

2022-04-25 12:49 UTC, winniepukki commented on components/CountrySelect/countries.json
> +	{ "code": "AM", "label": "Armenia", "phone": "374" },
The is no need in using the phone, please remove

2022-04-25 12:58 UTC, ymarkoff commented on components/CountrySelect/countries.json
> +	{ "code": "AM", "label": "Armenia", "phone": "374" },
Phone is sorted.

What are the previous messages, please quote. I can notice only this one
https://github.com/winniepukki/bonvoyage/pull/72#discussion_r854032227
but I'm not sure what the issue is.

2022-04-25 13:02 UTC, winniepukki requested changes

2022-04-25 13:46 UTC, ymarkoff commented on components/CountrySelect/countrySelect.js
> +                      srcSet={ `https://flagcdn.com/w40/${option.code.toLowerCase()}.png 2x` }
Do you mean destructuring? Sorted in latest comit.

2022-04-25 14:12 UTC, merged