add react-device-detect dependency and use it to restrict non-mobile …
winniepukki/bonvoyage pull request #75
Opened 2022-04-25 14:10 UTC by ymarkoff

#44

2022-04-25 14:34 UTC, winniepukki requested changes
@ymarkoff fix branch conflicts

2022-04-25 14:35 UTC, winniepukki commented
@ymarkoff why are the branching and commit strategies ignored, again???

2022-04-25 14:37 UTC, winniepukki commented
@ymarkoff why was the manual hook implementation ignored? what is the need for installing the package??

2022-04-25 14:38 UTC, ymarkoff commented
> @ymarkoff why are the branching and commit strategies ignored, again???

I'll make a new branch, I thought that I based this one on Staging, apologies.

2022-04-25 14:40 UTC, winniepukki commented
@ymarkoff please use: `feature/#<issue-nr>` for calling branches, and `feature/#<issue-nr> – <comment>` for commit messages. It is complicated to track changes and reference issues

2022-04-25 14:41 UTC, winniepukki commented
> I'll make a new branch, I thought that I based this one on Staging, apologies.

There is no need for a new branch, just change the target PR branch

2022-04-25 14:45 UTC, ymarkoff commented
> @ymarkoff please use: `feature/#<issue-nr>` for calling branches, and `feature/#<issue-nr> – <comment>` for commit messages. It is complicated to track changes and reference issues

Noted down.

2022-04-25 17:55 UTC, winniepukki requested changes
@ymarkoff please explain your choice for using such a variety of operating systems

2022-04-25 17:55 UTC, winniepukki commented on hooks/useMobileDetector/useMobileDetector.js
> +    return isMobile;
Please use the imperative programming:
```js
import { useState, useEffect } from "react";

export const useDeviceDetect = () => {
  const [isMobile, setMobile] = useState(false);

  useEffect(() => {
    const userAgent = typeof window.navigator === "undefined" ? "" : navigator.userAgent;
    const mobile = !!userAgent.match(
      /Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i
    );
    setMobile(mobile);
  }, []);

  return { isMobile };
};

export default useDeviceDetect;
```

2022-04-28 12:16 UTC, winniepukki approved these changes
@ymarkoff good. not merging, for now, considering Cypress is not good for testing the mobile environment. Leave it to me

2022-05-14 14:35 UTC, closed without merging