Feature/#52
winniepukki/bonvoyage pull request #78
Opened 2022-04-25 15:44 UTC by ymarkoff

Created a new branch with a single commit related to the Issue. Old branches are now deleted.

2022-04-25 17:58 UTC, winniepukki requested changes

2022-04-25 17:58 UTC, winniepukki commented on pages/journey.js
> +        // body: JSON.stringify(data) // body data type must match "Content-Type" header
Why need comments?

2022-04-25 17:58 UTC, winniepukki commented on pages/journey.js
> +        // 'Content-Type': 'application/json'
Comment?

2022-04-25 17:58 UTC, winniepukki commented on pages/journey.js
> +    const headers = {};
Function name doesn't tell much

2022-04-25 17:58 UTC, winniepukki commented on pages/journey.js
> +    postData('https://test.api.amadeus.com/v1/security/oauth2/token',
Any chance to use `function getRestrictions()` instead of the arrow functions?

2022-04-26 14:55 UTC, ymarkoff commented on pages/journey.js
> +    postData('https://test.api.amadeus.com/v1/security/oauth2/token',
I'm working on this, but I exceeded the API quota during testing. I'll finish testing and push ASAP.

2022-04-27 12:24 UTC, ymarkoff commented on pages/journey.js
> +    postData('https://test.api.amadeus.com/v1/security/oauth2/token',
Sorted in latest commit.

2022-04-27 12:26 UTC, ymarkoff commented
Currently console.log-ing restrictions from state to avoid "declared but never used" eslint error. This issue is just about drafting the requests, I don't have a meaningful way to "use" the restrictions currently.

2022-04-27 12:34 UTC, winniepukki requested changes

2022-04-27 12:34 UTC, winniepukki commented on pages/journey.js
> +    }
Please move the query to the `query` directory. We are not using any business logic in component files. Also, call this function properly, and follow the project arrow function calls conversion with `const`

2022-04-27 12:34 UTC, winniepukki commented on pages/journey.js
> +    }
Fetch what data? This is not intuitive. Also, move to the `query` directory

2022-04-27 12:34 UTC, winniepukki commented on pages/journey.js
> +    }, []);
No console logs should be in your commits

2022-04-27 12:34 UTC, winniepukki commented on pages/journey.js
> +
Same

2022-04-27 12:34 UTC, winniepukki commented on pages/journey.js
> +    }
Same

2022-04-27 12:34 UTC, winniepukki commented on pages/journey.js
> +                { JSON.stringify(restrictions) }
This is a monstrosity. Use the `<Dropdown />` component, and never ever do this again

2022-04-27 13:20 UTC, ymarkoff commented on pages/journey.js
> +    }
This is a general fetchData method, I wouldn't write the same code for each and every fetch call. As for moving it to a separate directory with queries, that's a pretty neat idea.

2022-04-27 14:23 UTC, winniepukki commented on pages/journey.js
> +    }
@ymarkoff is there a good reason for using this generic method? I don't personally think it is applicable within this context

2022-04-27 21:22 UTC, winniepukki requested changes

2022-04-27 21:22 UTC, winniepukki commented on queries/fetchRestrictions/fetchRestrictions.js
> +    return fetchData(requestString, authData.access_token);
Please return the data itself, but the function execution

2022-04-27 21:22 UTC, winniepukki commented on queries/fetchRestrictions/fetchRestrictions.js
> +function fetchRestrictions(authData, countryCode, cityCode) {
This still doesn't follow the `const` convesion. Are you reading the CR comments?

2022-04-27 21:22 UTC, winniepukki commented on queries/getRestrictions/getRestrictions.js
> +function getRestrictions(countryCode, cityCode = '') {
Same

2022-04-27 21:22 UTC, winniepukki commented on queries/postData/postData.js
> +    const headers = {
Same

2022-04-27 21:22 UTC, winniepukki commented on pages/journey.js
> +    }, []);
What is the further use of this?

2022-04-28 12:17 UTC, ymarkoff commented on pages/journey.js
> +    }, []);
An example of how the requests are supposed to be used. I guess I can remove them now that this is documented in previous commits.

2022-04-28 12:21 UTC, ymarkoff commented on pages/journey.js
> +    }
The same code would have to be used for any post request to Amadeus, I don't see an issue with extracting it into a reusable query. Makes the code in other queries more easily readable too.

2022-04-28 12:26 UTC, ymarkoff commented on queries/fetchRestrictions/fetchRestrictions.js
> +    return fetchData(requestString, authData.access_token);
I can't return the data, since we are working with promises here. Do you have a better idea of structuring the queries and the Journey component around unreliable time of delivery of the data by async functions?

2022-05-14 14:35 UTC, closed without merging